# Project information
site_name: "PayTechUz Guides"
site_description: 🟢 Guides, Examples, Tutorials
site_author: Hoosnick
site_url: https://docs.pay-tech.uz/
docs_dir: docs/src
site_dir: paytech

# Repository
repo_name: PayTechUz/paytech-guides
repo_url: https://github.com/PayTechUz/paytech-guides
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2023 PayTechUz

# Configuration
theme:
  name: material
  custom_dir: docs/src/overrides
  language: uz
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: Ubuntu
    code: Roboto Mono
  # icon:
  #   logo: material/cash-multiple
  logo: assets/logo.png

# Extras
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/+7Gn-JZ99TfgwZDNi
      name: "Biz telegramda"
    - icon: fontawesome/brands/github-alt
      link: https://github.com/PayTechUz/
      name: GitHub

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - meta
  - attr_list
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Payme Package:
      - payme-pkg/index.md
      - payme-pkg/setup.md
      - payme-pkg/merchant-api.md
      - payme-pkg/subscribe-api.md
      - payme-pkg/sandbox.md
  - Support: support.md

plugins:
  - search
  - i18n:
      default_language: uz
      default_language_only: false
      docs_structure: folder

      languages:
        - locale: uz
          default: true
          build: true
          name: "<img style='height: 10px; border: 0px;' alt='uz' src='https://flagicons.lipis.dev/flags/4x3/uz.svg' title='uzbek' /> O'zbekcha"
          nav_translations:
            Home: Kirish
            Payme Package: Payme Package
            Support: Texnik yordam

        - locale: en
          build: true
          name: "<img style='height: 10px; border: 0px;'' alt='en' src='https://flagicons.lipis.dev/flags/4x3/us.svg' title='english' /> English"
          site_name: "PayTechUz Guides"
          nav_translations:
            Home: Introduction
            Payme Package: Payme Package
            Support: Technical support

        - locale: ru
          build: true
          name: "<img style='height: 10px; border: 0px;'' alt='ru' src='https://flagicons.lipis.dev/flags/4x3/ru.svg' title='russian' /> Русский"
          site_name: "PayTechUz Гайды"
          nav_translations:
            Home: Введение
            Payme Package: Payme Package
            Support: Техническая поддержка
